[package]
name = "elusiv"
version = "0.1.0"
edition = "2021"

[features]
no-entrypoint = []
test-bpf = []

[dependencies]
# Chain storage
limbed_merkle = { git = "ssh://git@github.com/elusivcash/limbed_merkle.git" }
poseidon = { git = "ssh://git@github.com/elusivcash/poseidon.git" }

# Solana program
solana-program = "1.9.2"

# Groth16 verification
ark-bn254 = "0.3.0"
ark-ff = "0.3.0"
ark-groth16 = "0.3.0"


[dev-dependencies]
assert_matches = "1.4.0"
solana-program-test = "1.9.2"
solana-sdk = "1.9.2"
solana-validator = "1.9.2"
rand = "0.8.4"
base64 = "0.13.0"

# circom_verifier_key test dev-dependencies
num-bigint = "0.4"
num-traits = "0.2.0"

[lib]
name = "elusiv"
crate-type = ["cdylib", "lib"]