name: build

on:
  push:
    branches: [ master, nschapeler-fix-CLI ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Push to codecov.io
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV }}
      run: |
        git config --global credential.helper manager
        mkdir ~/.ssh
        echo "${{secrets.LIMBEDMERKLEBASE64}}" | base64 -d > ~/.ssh/id_rsa
        chmod 777 ~/.ssh
        eval "$(ssh-agent -s)"
        ssh-add ~/.ssh/id_rsa
        run: cargo build
        run: cargo install cargo-tarpaulin
        run: cargo tarpaulin --out Xml
