name: build

on:
  push:
    branches: [ master, nschapeler-fix-CLI ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - uses: webfactory/ssh-agent@v0.5.4
      with:
        ssh-private-key: >
          "-----BEGIN OPENSSH PRIVATE KEY-----
            b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAAAMwAAAAtzc2gtZW
            QyNTUxOQAAACAiGPrXfBhPIvg5n8DSrRKTbaDBk6NpeieilIZ14AsrdAAAALDeBgSv3gYE
            rwAAAAtzc2gtZWQyNTUxOQAAACAiGPrXfBhPIvg5n8DSrRKTbaDBk6NpeieilIZ14AsrdA
            AAAEDyc2lOH7e1h5nR4CgTPOM1MKmoETmS1/8h0uRgHgytjyIY+td8GE8i+DmfwNKtEpNt
            oMGTo2l6J6KUhnXgCyt0AAAAK2dpdEBnaXRodWIuY29tOmVsdXNpdmNhc2gvbGltYmVkX2
            1lcmtsZS5naXQBAg==
            -----END OPENSSH PRIVATE KEY-----"
    - name: Push to codecov.io
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV }}
      run: |
        cargo install cargo-tarpaulin
        cargo tarpaulin --out Xml
        bash <(curl -s https://codecov.io/bash) -X gcov -t $CODECOV_TOKEN
