name: build

on:
  push:
    branches: [ master, nschapeler-fix-CLI ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: webfactory/ssh-agent
    - uses: webfactory/ssh-agent@v0.5.4
      with:
            ssh-private-key: <(echo "${{secrets.LIMBEDMERKLEBASE64}}" | base64 -d)
    - name: Push to codecov.io
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV }}
      run: |
        cargo install cargo-tarpaulin
        cargo tarpaulin --out Xml
        bash <(curl -s https://codecov.io/bash) -X gcov -t $CODECOV_TOKEN
