name: build

on:
  push:
    branches: [ master, nschapeler-fix-CLI ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - uses: webfactory/ssh-agent@v0.5.4
      with:
        ssh-private-key: "-----BEGIN OPENSSH PRIVATE KEY-----b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAAAMwAAAAtzc2gtZWQyNTUxOQAAACCdie/+3IYHI9g3mo0xLF9sN219xgBYFAcBzMBQ33LonwAAAJC0u+BYtLvgWAAAAAtzc2gtZWQyNTUxOQAAACCdie/+3IYHI9g3mo0xLF9sN219xgBYFAcBzMBQ33LonwAAAECYzfV2PGeXipKjmkl7DVrvbb6MLK7HXuCunySZcNh/rZ2J7/7chgcj2DeajTEsX2w3bX3GAFgUBwHMwFDfcuifAAAACUVsdXNpdi1DSQECAwQ=-----END OPENSSH PRIVATE KEY-----"

    - name: Push to codecov.io
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV }}
      run: |
        cargo install cargo-tarpaulin
        cargo tarpaulin --out Xml
        bash <(curl -s https://codecov.io/bash) -X gcov -t $CODECOV_TOKEN
