name: build

on:
  push:
    branches: [ master, nschapeler-fix-CLI ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Push to codecov.io
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV }}
      run: |
        mkdir -p ~/.ssh
        ssh-add <(echo "$SSH_PRIVATE_KEY" | base64 -d)
        chmod 700 ~/.ssh
        cargo install cargo-tarpaulin
        cargo tarpaulin --out Xml
        bash <(curl -s https://codecov.io/bash) -X gcov -t $CODECOV_TOKEN
